// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RecruitmentTask.Contexts;

#nullable disable

namespace RecruitmentTask.Migrations
{
    [DbContext(typeof(ContactsContext))]
    [Migration("20240806082645_DataSeed")]
    partial class DataSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RecruitmentTask.Models.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SubCategory")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Contact", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDate = new DateTime(1957, 2, 6, 3, 25, 48, 0, DateTimeKind.Utc),
                            Category = "Personal",
                            Email = "wandacarter@yahoo.com",
                            FirstName = "Robin",
                            LastName = "Crane",
                            Password = "&jNraKMIa5",
                            PhoneNumber = "001-265-432-9150",
                            SubCategory = ""
                        },
                        new
                        {
                            Id = 2,
                            BirthDate = new DateTime(1950, 5, 5, 14, 37, 12, 0, DateTimeKind.Utc),
                            Category = "Other",
                            Email = "rgreen@gmail.com",
                            FirstName = "Monique",
                            LastName = "Moran",
                            Password = "(4#GAV_hYb",
                            PhoneNumber = "0118807176",
                            SubCategory = "civil"
                        },
                        new
                        {
                            Id = 3,
                            BirthDate = new DateTime(1958, 2, 13, 22, 49, 1, 0, DateTimeKind.Utc),
                            Category = "Business",
                            Email = "mgoodman@mccall.com",
                            FirstName = "Christine",
                            LastName = "Pena",
                            Password = "U9G5v(tt_l",
                            PhoneNumber = "001-516-329-1903x568",
                            SubCategory = "Boss"
                        },
                        new
                        {
                            Id = 4,
                            BirthDate = new DateTime(1928, 11, 22, 9, 15, 30, 0, DateTimeKind.Utc),
                            Category = "Business",
                            Email = "howardmichele@hotmail.com",
                            FirstName = "Benjamin",
                            LastName = "Nichols",
                            Password = "&9U*Soq(Xe",
                            PhoneNumber = "805-736-4268x6968",
                            SubCategory = "Client"
                        },
                        new
                        {
                            Id = 5,
                            BirthDate = new DateTime(1938, 3, 17, 11, 55, 44, 0, DateTimeKind.Utc),
                            Category = "Other",
                            Email = "robertbraun@gmail.com",
                            FirstName = "Jodi",
                            LastName = "Mclean",
                            Password = "0(08zLCd7H",
                            PhoneNumber = "9085445089",
                            SubCategory = "song"
                        },
                        new
                        {
                            Id = 6,
                            BirthDate = new DateTime(2017, 11, 15, 7, 42, 22, 0, DateTimeKind.Utc),
                            Category = "Personal",
                            Email = "charles97@hotmail.com",
                            FirstName = "Thomas",
                            LastName = "Tyler",
                            Password = "&2CyModfq2",
                            PhoneNumber = "837.087.5302x942",
                            SubCategory = ""
                        },
                        new
                        {
                            Id = 7,
                            BirthDate = new DateTime(2010, 9, 20, 19, 30, 0, 0, DateTimeKind.Utc),
                            Category = "Business",
                            Email = "brenda52@hotmail.com",
                            FirstName = "Michael",
                            LastName = "Williams",
                            Password = "*99$c8Keub",
                            PhoneNumber = "923.241.4303x53037",
                            SubCategory = "Client"
                        },
                        new
                        {
                            Id = 8,
                            BirthDate = new DateTime(1942, 3, 1, 23, 11, 5, 0, DateTimeKind.Utc),
                            Category = "Other",
                            Email = "johnsmary@everett.com",
                            FirstName = "Bradley",
                            LastName = "Riley",
                            Password = "%fPMZco*@3",
                            PhoneNumber = "001-995-809-8220x270",
                            SubCategory = "hit"
                        },
                        new
                        {
                            Id = 9,
                            BirthDate = new DateTime(2010, 10, 19, 6, 22, 35, 0, DateTimeKind.Utc),
                            Category = "Business",
                            Email = "owilson@hughes-martinez.com",
                            FirstName = "Jacob",
                            LastName = "Coleman",
                            Password = "*@y119L42q",
                            PhoneNumber = "+1-195-972-2281x7606",
                            SubCategory = "Boss"
                        },
                        new
                        {
                            Id = 10,
                            BirthDate = new DateTime(1923, 2, 28, 15, 18, 59, 0, DateTimeKind.Utc),
                            Category = "Other",
                            Email = "kthornton@yahoo.com",
                            FirstName = "Lindsay",
                            LastName = "Gray",
                            Password = "&S1BX9gsH8",
                            PhoneNumber = "245-124-6602x231",
                            SubCategory = "movement"
                        });
                });

            modelBuilder.Entity("RecruitmentTask.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("User", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
